spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: localhost

#  jackson:
#    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

wechat:
  appId: wx99ce5423b986e37c
  secret: cc64818ee310fa1a067d4f3881502d29
  openAppId:
  openAppSecret:
projecturl:
 wechatMpAuthorize: http://louyoan.s1.natapp.cc
 wechatOpenAuthorize:  http://louyoan.s1.natapp.cc
 sell: localhost:8080/sell/
 mchId: 980
 mchKey: 999
 keyPath: test/test.h
 notifyUrl: http://在微信授权回调地址中填写的公网备案域名/sell/pay/notify
logging:
  level:
    com.liuyuan.sell.dataobject.mapper: trace
